CREATE VIEW planet_osm_line AS
  SELECT
    osm_id,
    tags -> 'access' AS access,
    tags -> 'addr:housename' AS "addr:housename",
    tags -> 'addr:housenumber' AS "addr:housenumber",
    tags -> 'addr:interpolation' AS "addr:interpolation",
    tags -> 'admin_level' AS admin_level,
    tags -> 'aerialway' AS aerialway,
    tags -> 'aeroway' AS aeroway,
    tags -> 'amenity' AS amenity,
    tags -> 'area' AS area,
    tags -> 'barrier' AS barrier,
    tags -> 'bicycle' AS bicycle,
    tags -> 'brand' AS brand,
    tags -> 'bridge' AS bridge,
    tags -> 'boundary' AS boundary,
    tags -> 'building' AS building,
    tags -> 'construction' AS construction,
    tags -> 'covered' AS covered,
    tags -> 'culvert' AS culvert,
    tags -> 'cutting' AS cutting,
    tags -> 'denomination' AS denomination,
    tags -> 'disused' AS disused,
    tags -> 'embankment' AS embankment,
    tags -> 'foot' AS foot,
    tags -> 'generator:source' AS "generator:source",
    tags -> 'harbour' AS harbour,
    tags -> 'highway' AS highway,
    tags -> 'historic' AS historic,
    tags -> 'horse' AS horse,
    tags -> 'intermittent' AS intermittent,
    tags -> 'junction' AS junction,
    tags -> 'landuse' AS landuse,
    tags -> 'layer' AS layer,
    tags -> 'leisure' AS leisure,
    tags -> 'lock' AS lock,
    tags -> 'man_made' AS man_made,
    tags -> 'military' AS military,
    tags -> 'motorcar' AS motorcar,
    tags -> 'name' AS name,
    tags -> 'natural' AS natural,
    tags -> 'office' AS office,
    tags -> 'oneway' AS oneway,
    tags -> 'operator' AS operator,
    tags -> 'place' AS place,
    tags -> 'population' AS population,
    tags -> 'power' AS power,
    tags -> 'power_source' AS power_source,
    tags -> 'public_transport' AS public_transport,
    tags -> 'railway' AS railway,
    tags -> 'ref' AS ref,
    tags -> 'religion' AS religion,
    tags -> 'route' AS route,
    tags -> 'service' AS service,
    tags -> 'shop' AS shop,
    tags -> 'sport' AS sport,
    tags -> 'surface' AS surface,
    tags -> 'toll' AS toll,
    tags -> 'tourism' AS tourism,
    tags -> 'tower:type' AS "tower:type",
    tags -> 'tracktype' AS tracktype,
    tags -> 'tunnel' AS tunnel,
    tags -> 'water' AS water,
    tags -> 'waterway' AS waterway,
    tags -> 'wetland' AS wetland,
    tags -> 'width' AS width,
    tags -> 'wood' AS wood,
    z_order,
    way_area,
    way
  FROM hstore_line;

CREATE VIEW planet_osm_point AS
  SELECT
    osm_id,
    tags -> 'access' AS access,
    tags -> 'addr:housename' AS "addr:housename",
    tags -> 'addr:housenumber' AS "addr:housenumber",
    tags -> 'addr:interpolation' AS "addr:interpolation",
    tags -> 'admin_level' AS admin_level,
    tags -> 'aerialway' AS aerialway,
    tags -> 'aeroway' AS aeroway,
    tags -> 'amenity' AS amenity,
    tags -> 'area' AS area,
    tags -> 'barrier' AS barrier,
    tags -> 'bicycle' AS bicycle,
    tags -> 'brand' AS brand,
    tags -> 'bridge' AS bridge,
    tags -> 'boundary' AS boundary,
    tags -> 'building' AS building,
    tags -> 'capital' AS capital,
    tags -> 'construction' AS construction,
    tags -> 'covered' AS covered,
    tags -> 'culvert' AS culvert,
    tags -> 'cutting' AS cutting,
    tags -> 'denomination' AS denomination,
    tags -> 'disused' AS disused,
    tags -> 'ele' AS ele,
    tags -> 'embankment' AS embankment,
    tags -> 'foot' AS foot,
    tags -> 'generator:source' AS "generator:source",
    tags -> 'harbour' AS harbour,
    tags -> 'highway' AS highway,
    tags -> 'historic' AS historic,
    tags -> 'horse' AS horse,
    tags -> 'intermittent' AS intermittent,
    tags -> 'junction' AS junction,
    tags -> 'landuse' AS landuse,
    tags -> 'layer' AS layer,
    tags -> 'leisure' AS leisure,
    tags -> 'lock' AS lock,
    tags -> 'man_made' AS man_made,
    tags -> 'military' AS military,
    tags -> 'motorcar' AS motorcar,
    tags -> 'name' AS name,
    tags -> 'natural' AS natural,
    tags -> 'office' AS office,
    tags -> 'oneway' AS oneway,
    tags -> 'operator' AS operator,
    tags -> 'place' AS place,
    tags -> 'poi' AS poi,
    tags -> 'population' AS population,
    tags -> 'power' AS power,
    tags -> 'power_source' AS power_source,
    tags -> 'public_transport' AS public_transport,
    tags -> 'railway' AS railway,
    tags -> 'ref' AS ref,
    tags -> 'religion' AS religion,
    tags -> 'route' AS route,
    tags -> 'service' AS service,
    tags -> 'shop' AS shop,
    tags -> 'sport' AS sport,
    tags -> 'surface' AS surface,
    tags -> 'toll' AS toll,
    tags -> 'tourism' AS tourism,
    tags -> 'tower:type' AS "tower:type",
    tags -> 'tunnel' AS tunnel,
    tags -> 'water' AS water,
    tags -> 'waterway' AS waterway,
    tags -> 'wetland' AS wetland,
    tags -> 'width' AS width,
    tags -> 'wood' AS wood,
    way
  FROM hstore_point;

 CREATE VIEW planet_osm_polygon AS
  SELECT
    osm_id,
    tags -> 'access' AS access,
    tags -> 'addr:housename' AS "addr:housename",
    tags -> 'addr:housenumber' AS "addr:housenumber",
    tags -> 'addr:interpolation' AS "addr:interpolation",
    tags -> 'admin_level' AS admin_level,
    tags -> 'aerialway' AS aerialway,
    tags -> 'aeroway' AS aeroway,
    tags -> 'amenity' AS amenity,
    tags -> 'area' AS area,
    tags -> 'barrier' AS barrier,
    tags -> 'bicycle' AS bicycle,
    tags -> 'brand' AS brand,
    tags -> 'bridge' AS bridge,
    tags -> 'boundary' AS boundary,
    tags -> 'building' AS building,
    tags -> 'construction' AS construction,
    tags -> 'covered' AS covered,
    tags -> 'culvert' AS culvert,
    tags -> 'cutting' AS cutting,
    tags -> 'denomination' AS denomination,
    tags -> 'disused' AS disused,
    tags -> 'embankment' AS embankment,
    tags -> 'foot' AS foot,
    tags -> 'generator:source' AS "generator:source",
    tags -> 'harbour' AS harbour,
    tags -> 'highway' AS highway,
    tags -> 'historic' AS historic,
    tags -> 'horse' AS horse,
    tags -> 'intermittent' AS intermittent,
    tags -> 'junction' AS junction,
    tags -> 'landuse' AS landuse,
    tags -> 'layer' AS layer,
    tags -> 'leisure' AS leisure,
    tags -> 'lock' AS lock,
    tags -> 'man_made' AS man_made,
    tags -> 'military' AS military,
    tags -> 'motorcar' AS motorcar,
    tags -> 'name' AS name,
    tags -> 'natural' AS natural,
    tags -> 'office' AS office,
    tags -> 'oneway' AS oneway,
    tags -> 'operator' AS operator,
    tags -> 'place' AS place,
    tags -> 'population' AS population,
    tags -> 'power' AS power,
    tags -> 'power_source' AS power_source,
    tags -> 'public_transport' AS public_transport,
    tags -> 'railway' AS railway,
    tags -> 'ref' AS ref,
    tags -> 'religion' AS religion,
    tags -> 'route' AS route,
    tags -> 'service' AS service,
    tags -> 'shop' AS shop,
    tags -> 'sport' AS sport,
    tags -> 'surface' AS surface,
    tags -> 'toll' AS toll,
    tags -> 'tourism' AS tourism,
    tags -> 'tower:type' AS "tower:type",
    tags -> 'tracktype' AS tracktype,
    tags -> 'tunnel' AS tunnel,
    tags -> 'water' AS water,
    tags -> 'waterway' AS waterway,
    tags -> 'wetland' AS wetland,
    tags -> 'width' AS width,
    tags -> 'wood' AS wood,
    z_order,
    way_area,
    way
  FROM hstore_polygon;

 CREATE VIEW planet_osm_roads AS
  SELECT
    osm_id,
    tags -> 'access' AS access,
    tags -> 'addr:housename' AS "addr:housename",
    tags -> 'addr:housenumber' AS "addr:housenumber",
    tags -> 'addr:interpolation' AS "addr:interpolation",
    tags -> 'admin_level' AS admin_level,
    tags -> 'aerialway' AS aerialway,
    tags -> 'aeroway' AS aeroway,
    tags -> 'amenity' AS amenity,
    tags -> 'area' AS area,
    tags -> 'barrier' AS barrier,
    tags -> 'bicycle' AS bicycle,
    tags -> 'brand' AS brand,
    tags -> 'bridge' AS bridge,
    tags -> 'boundary' AS boundary,
    tags -> 'building' AS building,
    tags -> 'construction' AS construction,
    tags -> 'covered' AS covered,
    tags -> 'culvert' AS culvert,
    tags -> 'cutting' AS cutting,
    tags -> 'denomination' AS denomination,
    tags -> 'disused' AS disused,
    tags -> 'embankment' AS embankment,
    tags -> 'foot' AS foot,
    tags -> 'generator:source' AS "generator:source",
    tags -> 'harbour' AS harbour,
    tags -> 'highway' AS highway,
    tags -> 'historic' AS historic,
    tags -> 'horse' AS horse,
    tags -> 'intermittent' AS intermittent,
    tags -> 'junction' AS junction,
    tags -> 'landuse' AS landuse,
    tags -> 'layer' AS layer,
    tags -> 'leisure' AS leisure,
    tags -> 'lock' AS lock,
    tags -> 'man_made' AS man_made,
    tags -> 'military' AS military,
    tags -> 'motorcar' AS motorcar,
    tags -> 'name' AS name,
    tags -> 'natural' AS natural,
    tags -> 'office' AS office,
    tags -> 'oneway' AS oneway,
    tags -> 'operator' AS operator,
    tags -> 'place' AS place,
    tags -> 'population' AS population,
    tags -> 'power' AS power,
    tags -> 'power_source' AS power_source,
    tags -> 'public_transport' AS public_transport,
    tags -> 'railway' AS railway,
    tags -> 'ref' AS ref,
    tags -> 'religion' AS religion,
    tags -> 'route' AS route,
    tags -> 'service' AS service,
    tags -> 'shop' AS shop,
    tags -> 'sport' AS sport,
    tags -> 'surface' AS surface,
    tags -> 'toll' AS toll,
    tags -> 'tourism' AS tourism,
    tags -> 'tower:type' AS "tower:type",
    tags -> 'tracktype' AS tracktype,
    tags -> 'tunnel' AS tunnel,
    tags -> 'water' AS water,
    tags -> 'waterway' AS waterway,
    tags -> 'wetland' AS wetland,
    tags -> 'width' AS width,
    tags -> 'wood' AS wood,
    z_order,
    way_area,
    way
  FROM hstore_roads;
